version: '3.8'
services:
  db:
    container_name: nordcurrent-test-db
    image: postgres:15.1
    environment:
      POSTGRES_DB: nordcurrent-test-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
volumes:
  db_data:
